name: Keep Render Backend Awake

on:
  schedule:
    - cron: "*/10 * * * *" # Every 10 minutes
  workflow_dispatch:       # (Optional) allows manual run

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Render backend
        run: |
          curl -s --retry 2 https://nuvora-backend-fa1q.onrender.com/ > /dev/null
